const { getAIProvider } = require('../services/ai/aiProvider');

// Helper for exponential backoff on 429 errors
async function retryWithBackoff(fn, retries = 5, baseDelay = 10000) {
    for (let i = 0; i < retries; i++) {
        try {
            return await fn();
        } catch (error) {
            if (error.status === 429 || error.message.includes('429') || error.message.includes('Quota') || error.message.includes('Retry')) {
                const delay = baseDelay * Math.pow(2, i);
                console.log(`\n    ⏳ API Rate limit hit. Retrying in ${delay / 1000}s...`);
                await new Promise(res => setTimeout(res, delay));
            } else {
                throw error;
            }
        }
    }
    throw new Error('Max retries exceeded for API call');
}

class Evaluator {
    constructor() {
        this.provider = getAIProvider();
        // Fallback to ensuring genAI is available, because the adapter might be just a placeholder
        if (!this.provider.genAI) {
            console.warn("⚠️  Evaluator requires an active GEMINI_API_KEY. Set it in your environment.");
        }
    }

    /**
     * Evaluate a single fix generated by the AI
     * @returns {Promise<{score: number, failureType: string, explanation: string}>}
     */
    async evaluateFix(violation, fixObj) {
        if (!this.provider.genAI) {
            return { score: 0, failureType: "No API Key", explanation: "API key missing" };
        }

        const prompt = `You are an expert accessibility QA auditor. Evaluate the following AI-generated fix for an accessibility violation.

Original Violation:
- Description: ${violation.description}
- Original HTML: ${violation.html}
- CSS Selector: ${violation.selector}

AI Generated Fix:
- Fixed HTML: ${fixObj.fixedHtml}
- AI Explanation: ${fixObj.explanation}

Evaluate based on:
1. Valid HTML (no broken syntax)
2. True accessibility improvement (does it fix the specific WCAG issue?)
3. Simplicity (clean, minimal fix)
4. No over-modification (didn't break surrounding layout or context)

Respond ONLY with a valid JSON object matching this schema:
{
    "score": <number 0-10>,
    "failureType": "<string: 'none', 'invalid_html', 'missed_issue', 'hallucinated_aria', 'over_modification', 'other'>",
    "explanation": "<brief reason for the score>"
}`;

        try {
            const model = this.provider.genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
            const result = await retryWithBackoff(() => model.generateContent(prompt));
            let cleaned = result.response.text().trim();
            cleaned = cleaned.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/i, '');

            const evaluation = JSON.parse(cleaned);
            return {
                score: parseFloat(evaluation.score) || 0,
                failureType: evaluation.failureType || 'unknown',
                explanation: evaluation.explanation || ''
            };
        } catch (err) {
            console.error("Evaluation error:", err.message);
            return { score: 0, failureType: "evaluation_error", explanation: err.message };
        }
    }

    /**
     * Ask the AI to rewrite the base prompt stored in aiProvider.js
     * based on a list of failure patterns.
     */
    async improvePrompt(failurePatterns, currentPrompt) {
        if (!this.provider.genAI) return currentPrompt;

        const prompt = `You are an AI optimization expert. The current system prompt for fixing accessibility issues is producing the following common failures:

Failures detected:
${failurePatterns.map(f => `- ${f.type}: ${f.explanation}`).join('\n')}

Current Prompt to improve:
---
${currentPrompt}
---

Write a NEW, improved version of the prompt that explicitly prevents these failure patterns. 
Requirements:
1. Retain the JSON output format and required keys ("fixedHtml", "explanation", "confidence", "rootCause", "affectedUsers").
2. Add strict constraints to prevent the observed failures.
3. Be concise and authoritative.

Return ONLY the new prompt text, with no markdown code blocks or conversational text framing it.`;

        try {
            const model = this.provider.genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
            const result = await retryWithBackoff(() => model.generateContent(prompt));
            return result.response.text().trim();
        } catch (err) {
            console.error("Prompt improvement error:", err.message);
            return currentPrompt;
        }
    }
    /**
     * Generate architecture improvement suggestions (Scoring & Priority)
     */
    async generateArchitectureSuggestions(epochDataset) {
        if (!this.provider.genAI) {
            return {
                scoring: "Run with GEMINI_API_KEY to generate scoring logic improvements.",
                priority: "Run with GEMINI_API_KEY to generate priority engine improvements."
            };
        }

        const prompt = `Based on the following accessibility violations found during the QA scan run, generate two brief, actionable suggestions for modifying the system's hardcoded logic.
        
1. "Scoring System": Suggest how to tweak penalty weights or normalization based on DOM size.
2. "Priority Engine": Suggest how to adjust priority weights based on UI elements (e.g., buttons/forms vs static content).

Violations sample:
${epochDataset.slice(0, 10).map(i => `- ${i.violationDescription}`).join('\n')}

Return ONLY JSON: {"scoring": "suggestion text", "priority": "suggestion text"}`;

        try {
            const model = this.provider.genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
            const result = await retryWithBackoff(() => model.generateContent(prompt));
            let cleaned = result.response.text().trim().replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/i, '');
            return JSON.parse(cleaned);
        } catch (err) {
            return { scoring: "Error generating suggestion", priority: "Error generating suggestion" };
        }
    }
}

module.exports = Evaluator;
